"""
models.py — Pydantic Structured Output Models

These models enforce the exact JSON schema that the frontend expects.
They mirror the TypeScript `MitigationPlan` interface defined in
`src/lib/types.ts` of the Next.js frontend.

Used as `output_pydantic` on the final CrewAI task to guarantee
type-safe, parseable JSON output from the Routing Strategist agent.
"""

from typing import List, Literal
from pydantic import BaseModel, Field


class MitigationPlan(BaseModel):
    """
    A single mitigation plan generated by the Routing Strategist AI Agent.

    Maps exactly to the frontend TypeScript interface:
        interface MitigationPlan {
            id: string;
            name: string;
            strategy: string;
            description: string;
            estimatedCost: string;
            timeframe: string;
            riskLevel: 'Low' | 'Medium' | 'High';
            co2Impact: string;
            reliabilityScore: number;  // 0-100 integer
            details: string[];
        }
    """

    id: str = Field(
        description="Unique plan identifier, e.g. 'plan-a', 'plan-b', 'plan-c'"
    )
    name: str = Field(
        description="Short plan name, e.g. 'Plan A', 'Plan B', 'Plan C'"
    )
    strategy: str = Field(
        description="The core strategy title, e.g. 'Wait & Monitor', 'Reroute via Rail', 'Emergency Air Freight'"
    )
    description: str = Field(
        description="A 1-2 sentence summary of the plan's approach"
    )
    estimatedCost: str = Field(
        description="Human-readable cost estimate, e.g. '$340,000 — $410,000'"
    )
    timeframe: str = Field(
        description="Expected delivery timeframe, e.g. '12-16 days'"
    )
    riskLevel: Literal["Low", "Medium", "High"] = Field(
        description="Risk classification of this plan"
    )
    co2Impact: str = Field(
        description="Environmental impact relative to original route, e.g. '-18% vs. original sea route'"
    )
    reliabilityScore: int = Field(
        ge=0,
        le=100,
        description="Reliability percentage as an integer between 0 and 100"
    )
    details: List[str] = Field(
        description="A list of 3-5 bullet-point details explaining key considerations of this plan"
    )


class MitigationPlanList(BaseModel):
    """
    Wrapper model for the Routing Strategist's final output.
    Contains exactly 3 mitigation plans with varying risk/cost profiles.
    """

    plans: List[MitigationPlan] = Field(
        description="A list of exactly 3 mitigation plans, ordered from lowest cost/highest risk to highest cost/lowest risk"
    )
