"""
models.py — Pydantic Structured Output Models

These models enforce the exact JSON schema that the frontend expects.
They mirror the TypeScript interfaces defined in `src/lib/types.ts`
of the Next.js frontend.

Used as `output_pydantic` on CrewAI tasks to guarantee type-safe,
parseable JSON output from all three agents.
"""

from typing import List, Literal
from pydantic import BaseModel, Field


# ═══════════════════════════════════════════════════════════════════════
# TASK 1 — Global Risk Scout Output
# Mirrors: TypeScript `RiskScoutData` interface
# ═══════════════════════════════════════════════════════════════════════

class RiskScoutOutput(BaseModel):
    """Structured output from the Global Risk Scout AI Agent."""

    threatLevel: Literal["Critical", "High", "Medium", "Low"] = Field(
        description="Overall threat severity classification"
    )
    eventName: str = Field(
        description="Short name for the crisis event, e.g. 'Red Sea Maritime Disruption'"
    )
    eventDescription: str = Field(
        description="2-3 sentence description of what is happening and its immediate impact on global supply chains"
    )
    affectedPorts: List[str] = Field(
        description="List of affected ports with codes, e.g. ['Shanghai Yangshan (CNSHA)', 'Port Said (EGSAI)']"
    )
    weatherConditions: str = Field(
        description="Current weather and secondary environmental risks in the affected area"
    )
    newsHeadlines: List[str] = Field(
        description="3-5 relevant news headlines from major financial/logistics outlets"
    )
    geopoliticalFactors: List[str] = Field(
        description="2-4 geopolitical risk factors that may influence the crisis duration"
    )
    estimatedDuration: str = Field(
        description="Estimated disruption duration range, e.g. '7-14 business days (conservative estimate)'"
    )


# ═══════════════════════════════════════════════════════════════════════
# TASK 2 — Inventory Forecaster Output
# Mirrors: TypeScript `InventoryImpact` interface
# ═══════════════════════════════════════════════════════════════════════

class CriticalItem(BaseModel):
    """A single critical inventory item at risk of stockout."""

    name: str = Field(
        description="Component name, e.g. 'OLED Display Panel 6.7\"'"
    )
    currentStock: int = Field(
        description="Current stock level in units"
    )
    dailyBurnRate: int = Field(
        description="Daily consumption/burn rate in units per day"
    )
    daysUntilDepletion: int = Field(
        description="Calculated days until stock reaches zero at current burn rate"
    )
    reorderPoint: int = Field(
        description="Reorder point threshold based on safety stock policy"
    )
    status: Literal["Critical", "Warning", "Stable"] = Field(
        description="Inventory status classification based on days until depletion"
    )


class InventoryImpactOutput(BaseModel):
    """Structured output from the Inventory Forecaster AI Agent."""

    criticalItems: List[CriticalItem] = Field(
        description="List of 4-6 critical inventory items at risk, ordered by urgency (most critical first)"
    )
    totalSkusAffected: int = Field(
        description="Total number of SKUs impacted across all product lines"
    )
    revenueAtRisk: str = Field(
        description="Total revenue at risk in human-readable format, e.g. '$4.2M'"
    )
    productionLineImpact: str = Field(
        description="Summary of production line impact, e.g. '3 lines halt within 5 days'"
    )


# ═══════════════════════════════════════════════════════════════════════
# TASK 3 — Routing Strategist Output
# Mirrors: TypeScript `MitigationPlan` interface
# ═══════════════════════════════════════════════════════════════════════

class MitigationPlan(BaseModel):
    """
    A single mitigation plan generated by the Routing Strategist AI Agent.

    Maps exactly to the frontend TypeScript interface:
        interface MitigationPlan {
            id: string;
            name: string;
            strategy: string;
            description: string;
            estimatedCost: string;
            timeframe: string;
            riskLevel: 'Low' | 'Medium' | 'High';
            co2Impact: string;
            reliabilityScore: number;  // 0-100 integer
            details: string[];
        }
    """

    id: str = Field(
        description="Unique plan identifier, e.g. 'plan-a', 'plan-b', 'plan-c'"
    )
    name: str = Field(
        description="Short plan name, e.g. 'Plan A', 'Plan B', 'Plan C'"
    )
    strategy: str = Field(
        description="The core strategy title, e.g. 'Wait & Monitor', 'Reroute via Rail', 'Emergency Air Freight'"
    )
    description: str = Field(
        description="A 1-2 sentence summary of the plan's approach"
    )
    estimatedCost: str = Field(
        description="Human-readable cost estimate, e.g. '$340,000 — $410,000'"
    )
    timeframe: str = Field(
        description="Expected delivery timeframe, e.g. '12-16 days'"
    )
    riskLevel: Literal["Low", "Medium", "High"] = Field(
        description="Risk classification of this plan"
    )
    co2Impact: str = Field(
        description="Environmental impact relative to original route, e.g. '-18% vs. original sea route'"
    )
    reliabilityScore: int = Field(
        ge=0,
        le=100,
        description="Reliability percentage as an integer between 0 and 100"
    )
    details: List[str] = Field(
        description="A list of 3-5 bullet-point details explaining key considerations of this plan"
    )


class MitigationPlanList(BaseModel):
    """
    Wrapper model for the Routing Strategist's final output.
    Contains exactly 3 mitigation plans with varying risk/cost profiles.
    """

    plans: List[MitigationPlan] = Field(
        description="A list of exactly 3 mitigation plans, ordered from lowest cost/highest risk to highest cost/lowest risk"
    )

